[package]
name = "rdc2"
version = "0.1.0"
authors = ["Quentin Boyer <qbsecond@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
cstr_core = "0.1.2"
bstr = "0.2.11"

[dev-dependencies]
memmap = "0.7.0"
